
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class userMenu extends javax.swing.JFrame {
    
    int Mle;
    int id;
    
    Connection con;
    Connection con2;
    PreparedStatement ps;
    ResultSet rs;
    
    PreparedStatement ps2;
    ResultSet rs2;
    
    PreparedStatement ps3;
    ResultSet rs3;
    
    String db_driver = "com.mysql.cj.jdbc.Driver";
    
    
    public void afficherSolde() {
        
        try {
            Class.forName(db_driver);
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/resum5?zeroDateTimeBehavior=CONVERT_TO_NULL","root","121139");
            
            String sql2 = "SELECT id,Mle From loginout WHERE id = (SELECT MAX(id) FROM loginout)";
            ps2 = con.prepareStatement(sql2);
            rs2 = ps2.executeQuery();
            
            if (rs2.next()) {
                id = rs2.getInt(1);
                Mle = rs2.getInt(2);
            } 
            
           
            String sql = "SELECT Solde FROM informations WHERE Mle = ?";
            ps = con.prepareStatement(sql);
            ps.setInt(1,Mle);
            rs = ps.executeQuery();
            
        
            if (rs.next()) {
                int solde = rs.getInt(1);
               SoldeOut.setText(Integer.toString(solde)); 
        } 
                 
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(reservations.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form userMenu
     */
    public userMenu() {
        initComponents();
        setSize(770, 522);
        setLocation(200,100);
        afficherSolde();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thisWeek = new javax.swing.JButton();
        prevsWeek = new javax.swing.JButton();
        soldeLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        SoldeOut = new javax.swing.JLabel();
        backgroud1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("resum5 réservations");
        getContentPane().setLayout(null);

        thisWeek.setBackground(new java.awt.Color(204, 102, 255));
        thisWeek.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        thisWeek.setForeground(new java.awt.Color(255, 255, 255));
        thisWeek.setText("Voir mes réservations");
        thisWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thisWeekActionPerformed(evt);
            }
        });
        getContentPane().add(thisWeek);
        thisWeek.setBounds(410, 200, 220, 130);

        prevsWeek.setBackground(new java.awt.Color(102, 102, 255));
        prevsWeek.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prevsWeek.setForeground(new java.awt.Color(255, 255, 255));
        prevsWeek.setText("Reserver");
        prevsWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevsWeekActionPerformed(evt);
            }
        });
        getContentPane().add(prevsWeek);
        prevsWeek.setBounds(130, 200, 260, 130);

        soldeLabel.setText("SOLDE:");
        getContentPane().add(soldeLabel);
        soldeLabel.setBounds(530, 40, 60, 40);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jButton1.setText("Déconnexion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 120, 110, 25);

        SoldeOut.setText("0");
        getContentPane().add(SoldeOut);
        SoldeOut.setBounds(600, 40, 20, 40);

        backgroud1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/userMenu.png"))); // NOI18N
        getContentPane().add(backgroud1);
        backgroud1.setBounds(0, -5, 760, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thisWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thisWeekActionPerformed
        // TODO add your handling code here:
        nextWeekReserv f1 = new nextWeekReserv();
        f1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_thisWeekActionPerformed

    private void prevsWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevsWeekActionPerformed
        // TODO add your handling code here:
        reservations f2 = new reservations();
        f2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_prevsWeekActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
            Class.forName(db_driver);
            con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/resum5?zeroDateTimeBehavior=CONVERT_TO_NULL","root","121139");
            
            String sql3 = "DELETE FROM loginout WHERE id = ?";
            ps3 = con2.prepareStatement(sql3);
            ps3.setInt(1,id);
            int rs3 = ps3.executeUpdate();
                 
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(reservations.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        LoginUser f3 = new LoginUser();
        f3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userMenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SoldeOut;
    private javax.swing.JLabel backgroud1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton prevsWeek;
    private javax.swing.JLabel soldeLabel;
    private javax.swing.JButton thisWeek;
    // End of variables declaration//GEN-END:variables
}
